--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ItsToxicGG/MurderMysteryy
build-by-default: true
branches:
- main
projects:
  MurderMysteryy:
    path: ""
    libs:
      - src: Ifera/ScoreFactory/ScoreFactory
        version: ^3.1.0

...
